### ISSUE TITLE
it's cool but

### ISSUE THREAD

**Issue by mendrezjan** [vesche/proxy-scrape#1]
![screenshot from 2018-05-14 13-53-48](https://user-images.githubusercontent.com/16321229/39980396-4fc15c96-577e-11e8-90f5-6e9e7df84849.png)

**Comment by vesche** [comment]
Sorry for the late reply, yeah this tool depends on the TorVPN proxy listing populating IP's. I'm not sure why their list isn't working anymore. I've added a defunct message to the README.
